version: 2

updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
    groups:
      deps:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
