name: commit
on:
  push:
    paths-ignore:
      - "**/*.md"

env:
  APPLICATION_NAME: hiiretail-pubsub-unwrapper
  IMAGE_NAME: eu.gcr.io/extenda/hiiretail-pubsub-unwrapper
  GIT_BRANCH: ${{ github.ref_name }}
  GIT_COMMIT: ${{ github.sha }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Restore npm build
        uses: ./.github/actions/restore-build

      - name: Cache Sonar binary
        uses: actions/cache@v3
        env:
          cache-name: cache-sonar-binary
        with:
          path: /home/runner/.sonar/native-sonar-scanner
          key: ${{ runner.os }}-cache-sonar-binary
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}

      - name: Lint javascript
        run: npm run lint:js

      - name: Unit tests
        run: npm test -- --ci --runInBand

      - name: Analyze with SonarCloud
        uses: extenda/actions/sonar-scanner@v0
        with:
          sonar-host: https://sonarcloud.io
          service-account-key: ${{ secrets.SECRET_AUTH }}

  release:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs:
      - test
    outputs:
      release-tag: ${{ steps.release.outputs.release-tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create release
        uses: extenda/actions/conventional-release@v0
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: extenda/actions/setup-gcloud@v0
        with:
          service-account-key: ${{ secrets.GCLOUD_AUTH_PROD }}

      - name: Build and push image to GCP
        run: |
          gcloud --quiet auth configure-docker
          docker build -t ${{ env.IMAGE_NAME }}:${{ github.sha }} .
          docker push ${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Attest image
        uses: extenda/actions/binary-auth-attestation@v0
        with:
          image-path: ${{ env.IMAGE_NAME }}
          service-account-key: ${{ secrets.GCLOUD_AUTH_PROD }}

      - name: Add release tags to Docker image
        run: |
          gcloud container images add-tag \
            ${{ env.IMAGE_NAME }}:${{ github.sha }} \
            ${{ env.IMAGE_NAME }}:${{ steps.release.outputs.release-tag }}
