name: commit
on:
  push:
    paths-ignore:
      - "**/*.md"

env:
  IMAGE_NAME: extenda/hiiretail-pubsub-unwrapper
  GIT_BRANCH: ${{ github.ref_name }}
  GIT_COMMIT: ${{ github.sha }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Restore npm build
        uses: ./.github/actions/restore-build

      - name: Cache Sonar binary
        uses: actions/cache@v3
        env:
          cache-name: cache-sonar-binary
        with:
          path: /home/runner/.sonar/native-sonar-scanner
          key: ${{ runner.os }}-cache-sonar-binary
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}

      - name: Lint javascript
        run: npm run lint:js

      - name: Unit tests
        run: npm test -- --ci --runInBand

      - name: Analyze with SonarCloud
        uses: extenda/actions/sonar-scanner@v0
        with:
          sonar-host: https://sonarcloud.io
          service-account-key: ${{ secrets.SECRET_AUTH }}

      - name: build docker
        run: docker buildx build -t ${{ env.IMAGE_NAME }} .

  release:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs:
      - test
    outputs:
      release-tag: ${{ steps.release.outputs.release-tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create release
        uses: extenda/actions/conventional-release@v0
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: extenda/actions/gcp-secret-manager@v0
        with:
          service-account-key: ${{ secrets.SECRET_AUTH }}
          secrets: |
            DOCKER_PASSWORD: dockerhub-password
            DOCKER_USERNAME: dockerhub-username

      - name: Push to DockerHub
        uses: extenda/actions/docker@v0
        with:
          image: ${{ env.IMAGE_NAME }}
          tag: ${{ steps.release.outputs.release-tag }}
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
